# Generated by Django 3.1.7 on 2021-02-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('short_description', models.CharField(blank=True, max_length=249, null=True)),
                ('long_description', models.TextField(blank=True, max_length=10000, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=249, null=True)),
                ('expected_budget', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('collected_money', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_fund', models.ManyToManyField(blank=True, null=True, to='donation.FundType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
