# Generated by Django 3.1.7 on 2021-02-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_activity', '0004_remove_projectsgallary_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundtype',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
