# Generated by Django 3.1.7 on 2022-01-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_activity', '0005_auto_20210219_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='will_show_front_page',
            field=models.BooleanField(default=False),
        ),
    ]
