# Generated by Django 3.1.7 on 2021-02-19 13:33

from django.db import migrations, models
import organization_activity.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_activity', '0002_auto_20210219_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsgallary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=organization_activity.models.project_image_upload_path),
        ),
    ]
