# Generated by Django 3.1.7 on 2021-02-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization_activity', '0003_auto_20210219_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsgallary',
            name='name',
        ),
    ]
