# Generated by Django 3.1.7 on 2021-04-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_auto_20210410_1514'),
        ('organization_activity', '0005_auto_20210219_1821'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbalance',
            name='fund_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donation.fundtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashbalance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_activity.projects'),
        ),
        migrations.AlterField(
            model_name='debitrecord',
            name='from_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.fundtype'),
        ),
    ]
