# Generated by Django 3.1.7 on 2021-05-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20210410_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitrecord',
            name='title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
