# Generated by Django 3.1.7 on 2021-05-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_debitrecord_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitrecord',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounting.debitcategory'),
            preserve_default=False,
        ),
    ]
