# Generated by Django 3.1.7 on 2021-05-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_debitrecord_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbalance',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='debitrecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
