# Generated by Django 3.1.7 on 2021-02-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization/')),
                ('short_description', models.CharField(blank=True, max_length=249, null=True)),
                ('long_description', models.TextField(blank=True, max_length=10000, null=True)),
                ('address', models.CharField(max_length=249)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('website', models.URLField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
