# Generated by Django 3.1.7 on 2021-04-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_details', '0003_auto_20210219_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_photo', models.ImageField(upload_to='organization/cover/')),
                ('position', models.SmallIntegerField()),
                ('h1_text', models.CharField(max_length=250)),
                ('h2_text', models.CharField(max_length=250)),
                ('details_text', models.CharField(max_length=250)),
                ('button_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
