# Generated by Django 3.1.7 on 2021-04-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_details', '0004_coverphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('phn', models.CharField(db_index=True, default=1, max_length=11)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
