# Generated by Django 3.1.7 on 2021-04-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_details', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='abd@hsdj.dsj', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phn',
            field=models.CharField(blank=True, db_index=True, default=1, max_length=11, null=True),
        ),
    ]
