# Generated by Django 3.1.7 on 2021-04-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_details', '0006_auto_20210417_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phn',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
