# Generated by Django 3.1.7 on 2021-04-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_details', '0009_quote_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverphoto',
            name='button_text',
            field=models.CharField(default='click', max_length=100),
            preserve_default=False,
        ),
    ]
