# Generated by Django 3.1.7 on 2021-04-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_details', '0010_coverphoto_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverphoto',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coverphoto',
            name='details_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='coverphoto',
            name='h1_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='coverphoto',
            name='h2_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
