# Generated by Django 3.1.7 on 2021-05-02 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organization_details', '0012_auto_20210430_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=249)),
                ('details', models.TextField(max_length=1000)),
                ('published_date', models.DateTimeField(default=datetime.datetime(2021, 5, 2, 17, 28, 46, 74393, tzinfo=utc))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
