# Generated by Django 3.1.7 on 2022-01-28 22:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('organization_details', '0014_auto_20220129_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 22, 0, 2, 13830, tzinfo=utc)),
        ),
    ]
