# Generated by Django 3.1.7 on 2021-02-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_activity', '0002_auto_20210219_1330'),
        ('organization_details', '0002_transectionaccounts_transectionaccountscategory'),
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('donation_details', models.CharField(blank=True, max_length=249, null=True)),
                ('is_visiable_to_public', models.BooleanField(default=True)),
                ('donated_in_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_activity.projects')),
                ('donated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_details.transectionaccounts')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FundType',
        ),
    ]
