# Generated by Django 3.1.7 on 2021-04-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_details', '0004_coverphoto'),
        ('organization_activity', '0005_auto_20210219_1821'),
        ('donation', '0003_auto_20210219_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donor_pic/'),
        ),
        migrations.CreateModel(
            name='RepeatedDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('donation_details', models.CharField(blank=True, max_length=249, null=True)),
                ('frequency', models.CharField(choices=[('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='M', max_length=2)),
                ('is_visiable_to_public', models.BooleanField(default=True)),
                ('donated_in_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization_activity.projects')),
                ('donated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_details.transectionaccounts')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.donor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
