# Generated by Django 3.1.7 on 2021-04-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_auto_20210410_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='donationrecord',
            name='fund_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donation.fundtype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repeateddonation',
            name='fund_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='donation.fundtype'),
            preserve_default=False,
        ),
    ]
