# Generated by Django 3.1.7 on 2021-05-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_auto_20210501_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrecord',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('F', 'Failed'), ('S', 'Success')], default='P', max_length=2),
        ),
    ]
