# Generated by Django 3.1.7 on 2021-05-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_donationrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='phone',
            field=models.CharField(db_index=True, default='12345678', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
