# Generated by Django 3.1.7 on 2022-01-28 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization_activity', '0006_projects_will_show_front_page'),
        ('donation', '0008_auto_20210502_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrecord',
            name='donated_in_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_project', to='organization_activity.projects'),
        ),
    ]
