# Generated by Django 3.1.7 on 2021-02-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_details', '0003_auto_20210219_1821'),
        ('organization_activity', '0005_auto_20210219_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DebitRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('debited_by', models.CharField(default='Admin', max_length=50)),
                ('debited_to', models.CharField(default='Admin', max_length=100)),
                ('justification', models.TextField(blank=True, max_length=500, null=True)),
                ('comment', models.CharField(blank=True, max_length=249, null=True)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_details.transectionaccounts')),
                ('from_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_activity.fundtype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization_activity.projects')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.IntegerField(default=0)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization_activity.projects')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
