# Generated by Django 3.1.7 on 2021-02-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_details', '0002_transectionaccounts_transectionaccountscategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='transectionaccounts',
            name='current_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transectionaccounts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organizationdetails',
            name='logo',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='organization/'),
        ),
        migrations.AlterField(
            model_name='organizationdetails',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transectionaccounts',
            name='account_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transectionaccounts',
            name='bank_name',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='transectionaccountscategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
